const MushroomCup = {
  lc: {
    title: "Luigi Circuit",
    data: [
      { country: "us", player: "Kasey", timeData: { minutes: 1, seconds: 8, milliseconds: 733 }, link: "https://www.youtube.com/watch?v=HPcvNS8QFVI", ghost: "https://chadsoft.co.uk/time-trials/rkgd/CF/0F/CCB3BBD6ACD5591FC092310D0373B26978A0.html" },
      { country: "ca", player: "Cole", timeData: { minutes: 1, seconds: 8, milliseconds: 774 }, link: "https://youtube.com/watch?v=-OQhxq2JZ3w", ghost: "https://www.chadsoft.co.uk/time-trials/rkgd/DB/E0/9D0E74FC89F62B45F42E5ACD3B0556B71026.html" },
      { country: "ca", player: "Daniel K", timeData: { minutes: 1, seconds: 8, milliseconds: 941 }, link: "https://www.youtube.com/watch?v=8CSaegSz-PY", ghost: "dummy" },
      { country: "mx", player: "AaronW", timeData: { minutes: 1, seconds: 8, milliseconds: 968 }, link: "https://youtu.be/vX4jLHx5dX0", ghost:"dummy" },
      { country: "nl", player: "SwareJonge", timeData: { minutes: 1, seconds: 8, milliseconds: 989 }, link:"dummy", ghost:"dummy" },
      { country: "us", player: "Sosis", timeData: { minutes: 1, seconds: 9, milliseconds: 50 }, link: "https://m.youtube.com/watch?v=qC2SsuTywVo&feature=youtu.be", ghost: "dummy" },
      { country: "us", player: "Paul M.", timeData: { minutes: 1, seconds: 9, milliseconds: 66 }, link: "https://www.youtube.com/watch?v=QFU-HmQe2Nw&t=0s", ghost: "dummy" },
      { country: "us", player: "Jack", timeData: { minutes: 1, seconds: 9, milliseconds: 81 }, link: "https://www.youtube.com/watch?v=mOK1VXDBrMo", ghost: "dummy" },
      { country: "fr", player: "Don Capri", timeData: { minutes: 1, seconds: 9, milliseconds: 118 }, link: "https://youtu.be/1G4-5pceqlU", ghost: "dummy" },
      { country: "gb", player: "Sword", timeData: { minutes: 1, seconds: 9, milliseconds: 118 }, link: "https://www.youtube.com/watch?v=5QvYCL5El2o", ghost: "dummy" },
    ],
  },
  mmm: {
    title: "Moo Moo Meadows",
    data: [
      { country: "us", player: "Sosis", timeData: { minutes: 1, seconds: 15, milliseconds: 273 }, link:"dummy", ghost:"dummy" },
      { country: "us", player: "Logan", timeData: { minutes: 1, seconds: 15, milliseconds: 351 }, link:"dummy", ghost:"dummy" },
      { country: "us", player: "Kasey", timeData: { minutes: 1, seconds: 15, milliseconds: 362 }, link:"dummy", ghost:"dummy" },
      { country: "us", player: "ZCubed", timeData: { minutes: 1, seconds: 15, milliseconds: 444 }, link:"dummy", ghost:"dummy" },
      { country: "us", player: "Steve", timeData: { minutes: 1, seconds: 15, milliseconds: 456 }, link:"dummy", ghost:"dummy" },
      { country: "us", player: "Eight", timeData: { minutes: 1, seconds: 15, milliseconds: 519 }, link:"dummy", ghost:"dummy" },
      { country: "us", player: "Vincent B.", timeData: { minutes: 1, seconds: 15, milliseconds: 584 }, link:"dummy", ghost:"dummy" },
      { country: "no", player: "Fox", timeData: { minutes: 1, seconds: 15, milliseconds: 658 }, link:"dummy", ghost:"dummy" },
      { country: "us", player: "Blaze", timeData: { minutes: 1, seconds: 15, milliseconds: 662 }, link:"dummy", ghost:"dummy" },
      { country: "us", player: "Paul M.", timeData: { minutes: 1, seconds: 15, milliseconds: 662 }, link:"dummy", ghost:"dummy" },
    ],
  },
  mg: {
    title: "Mushroom Gorge",
    data: [
      { country: "at", player: "Alperen", timeData: { minutes: 1, seconds: 40, milliseconds: 494 }, link:"dummy", ghost:"dummy" },
      { country: "us", player: "Logan", timeData: { minutes: 1, seconds: 40, milliseconds: 580 }, link:"dummy", ghost:"dummy" },
      { country: "us", player: "Justin", timeData: { minutes: 1, seconds: 40, milliseconds: 723 }, link:"dummy", ghost:"dummy" },
      { country: "us", player: "Connor", timeData: { minutes: 1, seconds: 40, milliseconds: 741 }, link:"dummy", ghost:"dummy" },
      { country: "gb", player: "Eclipse", timeData: { minutes: 1, seconds: 40, milliseconds: 849 }, link:"dummy", ghost:"dummy" },
      { country: "ie", player: "Daniel", timeData: { minutes: 1, seconds: 40, milliseconds: 870 }, link:"dummy", ghost:"dummy" },
      { country: "gb", player: "Luke", timeData: { minutes: 1, seconds: 40, milliseconds: 974 }, link:"dummy", ghost:"dummy" },
      { country: "us", player: "Ryan", timeData: { minutes: 1, seconds: 40, milliseconds: 994 }, link:"dummy", ghost:"dummy" },
      { country: "us", player: "Zuspii", timeData: { minutes: 1, seconds: 41, milliseconds: 2 }, link:"dummy", ghost:"dummy" },
      { country: "gb", player: "Scorpion", timeData: { minutes: 1, seconds: 41, milliseconds: 16 }, link:"dummy", ghost:"dummy" },
    ],
    glitchData: [
      { country: "us", player: "Idriz", timeData: { minutes: 0, seconds: 19, milliseconds: 758 }, link:"dummy", ghost:"dummy" },
      { country: "us", player: "Bryce", timeData: { minutes: 0, seconds: 20, milliseconds: 36 }, link:"dummy", ghost:"dummy" },
      { country: "us", player: "Ray", timeData: { minutes: 0, seconds: 21, milliseconds: 653 }, link:"dummy", ghost:"dummy" },
      { country: "us", player: "FoxGaming", timeData: { minutes: 0, seconds: 24, milliseconds: 174 }, link:"dummy", ghost:"dummy" },
      { country: "us", player: "Kenny", timeData: { minutes: 0, seconds: 26, milliseconds: 9 }, link:"dummy", ghost:"dummy" },
      { country: "gb", player: "Sam", timeData: { minutes: 0, seconds: 26, milliseconds: 769 }, link:"dummy", ghost:"dummy" },
      { country: "fi", player: "Arvo", timeData: { minutes: 0, seconds: 27, milliseconds: 959 }, link:"dummy", ghost:"dummy" },
      { country: "ie", player: "Shane", timeData: { minutes: 0, seconds: 28, milliseconds: 55 }, link:"dummy", ghost:"dummy" },
      { country: "us", player: "Guy", timeData: { minutes: 0, seconds: 28, milliseconds: 224 }, link:"dummy", ghost:"dummy" },
      { country: "jp", player: "Kisaragi", timeData: { minutes: 0, seconds: 28, milliseconds: 292 }, link:"dummy", ghost:"dummy" },
    ]
  },
  tf: {
    title: "Toad's Factory",
    data: [
      { country: "us", player: "Logan", timeData: { minutes: 1, seconds: 49, milliseconds: 39 }, link:"dummy", ghost:"dummy" },
      { country: "us", player: "Connor", timeData: { minutes: 1, seconds: 49, milliseconds: 156 }, link:"dummy", ghost:"dummy" },
      { country: "no", player: "Barney", timeData: { minutes: 1, seconds: 49, milliseconds: 157 }, link:"dummy", ghost:"dummy" },
      { country: "gb", player: "Luke", timeData: { minutes: 1, seconds: 49, milliseconds: 157 }, link:"dummy", ghost:"dummy" },
      { country: "at", player: "Alperen", timeData: { minutes: 1, seconds: 49, milliseconds: 227 }, link:"dummy", ghost:"dummy" },
      { country: "no", player: "Fox", timeData: { minutes: 1, seconds: 49, milliseconds: 230 }, link:"dummy", ghost:"dummy" },
      { country: "us", player: "Ryan", timeData: { minutes: 1, seconds: 49, milliseconds: 291 }, link:"dummy", ghost:"dummy" },
      { country: "de", player: "Akiza", timeData: { minutes: 1, seconds: 49, milliseconds: 327 }, link:"dummy", ghost:"dummy" },
      { country: "us", player: "Steve", timeData: { minutes: 1, seconds: 49, milliseconds: 329 }, link:"dummy", ghost:"dummy" },
      { country: "gb", player: "David", timeData: { minutes: 1, seconds: 49, milliseconds: 373 }, link:"dummy", ghost:"dummy" },
    ],
    glitchData: [
      { country: "us", player: "Logan", timeData: { minutes: 1, seconds: 44, milliseconds: 178 }, link:"dummy", ghost:"dummy" },
      { country: "au", player: "Mitch", timeData: { minutes: 1, seconds: 44, milliseconds: 819 }, link:"dummy", ghost:"dummy" },
      { country: "us", player: "Eli", timeData: { minutes: 1, seconds: 45, milliseconds: 26 }, link:"dummy", ghost:"dummy" },
      { country: "au", player: "Jyran", timeData: { minutes: 1, seconds: 45, milliseconds: 34 } },
      { country: "gb", player: "Ross", timeData: { minutes: 1, seconds: 45, milliseconds: 106 }, link:"dummy", ghost:"dummy" },
      { country: "jp", player: "Nugget", timeData: { minutes: 1, seconds: 45, milliseconds: 195 }, link:"dummy", ghost:"dummy" },
      { country: "us", player: "Vincent N.", timeData: { minutes: 1, seconds: 45, milliseconds: 207 }, link:"dummy", ghost:"dummy" },
      { country: "ca", player: "Zilla", timeData: { minutes: 1, seconds: 45, milliseconds: 212 }, link:"dummy", ghost:"dummy" },
      { country: "us", player: "Dev", timeData: { minutes: 1, seconds: 45, milliseconds: 309 }, link:"dummy", ghost:"dummy" },
      { country: "fi", player: "Karhuma", timeData: { minutes: 1, seconds: 45, milliseconds: 341 }, link:"dummy", ghost:"dummy" },
    ],
  },
};

export default MushroomCup;